#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 7878" \
        cd /app/radarr/bin s6-setuidgid abc /app/radarr/bin/Radarr \
        -nobrowser -data=/config
