#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*         This image is for development only         *
*                                                    *
*              Use at your own peril                 *
* It will likely have bugs and not function properly *
*                                                    *
*                                                    *
******************************************************
******************************************************'
